# -*- coding: utf-8 -*-
"""CountingFalling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L4-1vF5e-6uF1lgzd49n68rv-67QKqO6
"""

score = input().split()
count = 0
for i in score:
  if int(i) < 60:
    count = count + 1
print("不及格人數：",count)